apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-inference-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dubeygaurav-tech/ai-platform-infra' # Replace with your repo URL
    targetRevision: HEAD
    path: .
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai-workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true