apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: monitoring
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 60.0.0 # Pin your versions!
    helm:
      values: |
        grafana:
          adminPassword: "prom-operator"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring