apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: inference-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dubeygaurav-tech/ai-platform-infra'
    targetRevision: HEAD
    path: manifests/inference-server/ # Look here for raw YAMLs
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ai-workloads